# Generated by Django 3.1.4 on 2020-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthyYoung', models.PositiveIntegerField(default=0)),
                ('healthyYoungFreerider', models.PositiveIntegerField(default=0)),
                ('sickYoung', models.PositiveIntegerField(default=0)),
                ('healthyElderly', models.PositiveIntegerField(default=0)),
                ('healthyElderlyFreerider', models.PositiveIntegerField(default=0)),
                ('sickElderly', models.PositiveIntegerField(default=0)),
                ('vaccines', models.PositiveIntegerField(default=0)),
                ('timeSpan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': [],
            },
        ),
    ]
